### ISSUE TITLE
Pokemon species from Paldea have wrong id

### ISSUE THREAD

**Issue by tillfox** [PokeAPI/pokeapi#812]
The ids of pokemons from Paldea region are inconsistent with the actual numbering reported on serebii.net. This problem obviously exists even on other relations, like "pokemon_stats" and "pokemon". The ids should be changed evenly.

![Paldea-Pokemons-Ids-Inconsistent](https://user-images.githubusercontent.com/15571805/211668566-2fc07724-bc6e-4a17-a4af-3088a845b6a8.png)

**Comment by NathanGuidry** [comment]
came here to say this. Everything is good for me up until #917.

**Comment by tillfox** [comment]
> came here to say this. Everything is good for me up until #917.

Yes, I can confirm. To solve this problem we can split the resolution in two steps:
- Identify a mathematical relation (a set of couples (int, int)) that pairs the wrong id with the right one. This should be done manually, someone should check the wrong ids and report the correct ones, maybe in a csv file, in which every line is a couple of ids (wrong and right) separated by comma (oc). In short words someone should manually report all the wrong ids.
- Create a script that assigns the right id to the tuples in the various tables (relations). This is the easy part (In term of waste of time), I can do this.

**Comment by NathanGuidry** [comment]
if you could be a little more specific with the formatting, I might be willing to help. would you want it like (wrongId1, rightId1), (wrongId2, rightId2), (wrongId3, rightId3), etc.?

**Comment by Naramsim** [comment]
Hi, are you talking about the same issue @oneirocosm mentioned here?

https://github.com/PokeAPI/pokeapi/pull/793#issuecomment-1369192812

Let me understand, the new pokemon have been released but their ID hasn't?

**Comment by tillfox** [comment]
> Hi, are you talking about the same issue @oneirocosm mentioned here?
> 
> [#793 (comment)](https://github.com/PokeAPI/pokeapi/pull/793#issuecomment-1369192812)
> 
> Let me understand, the new pokemon have been released but their ID hasn't?

Yeah, the problem is the same mentioned there. Now we have the official ids, you can find them here : https://www.serebii.net/pokemon/nationalpokedex.shtml

**Comment by tillfox** [comment]
> if you could be a little more specific with the formatting, I might be willing to help. would you want it like (wrongId1, rightId1), (wrongId2, rightId2), (wrongId3, rightId3), etc.?

Thanks, the format should be:
wrong_id,correct_id
917,982
918,917
919,918
920,919
921,920
922,953
923,954
...

**Comment by Naramsim** [comment]
If you know the correct ID feel free of submitting a PR fixing the order and the gaps

**Comment by tillfox** [comment]
> Here it is. Be wary of the null #980 and #987 that I mentioned earlier. [wrongIDs.csv](https://github.com/PokeAPI/pokeapi/files/10407921/wrongIDs.csv)

Wow, good job @NathanGuidry! A fast work!

**Comment by tillfox** [comment]
> If you know the correct ID feel free of submitting a PR fixing the order and the gaps

Perfect, It will be easy to create a script to fix this, but there is a problem. This change will affect all these relations:

- encounters (pokemon_id)
- pokemon (id, species_id)*
- pokemon_abilities (pokemon_id)
- pokemon_form_generations (pokemon_form_id)
- pokemon_form_names (pokemon_form_id)
- pokemon_forms (id, pokemon_id)*
- pokemon_species (id, evolves_from_species_id)*
- pokemon_species_flavor_text (species_id)
- pokemon_species_names (pokemon_species_id)*
- pokemon_stats (pokemon_id)
- pokemon_types (pokemon_id)

* = Contains Paldea Pokemon data in master

Just the ones with star could give problems related to concurrency, but if someone else merges changes made using the wrong Ids from another branch, we'll have inconsistent data...

In addition to that, do I have permissions to directly push a branch on pokeapi, or should I just send you the updated files, so you can commit them? @Naramsim

**Comment by tillfox** [comment]
> Hi, we'll need to change the `id`s of all the files at the same time.
> 
> There are currently two PRs that still use the old `id`s: #795 and #806. Done by @giginet
> 
> So I think the best is to wait for me to review those PRs and have them merged. Then we can run your script which should change the `id`s in many files.
> 
> I'd also like to know what @giginet thinks.
> 
> Currently, you @tillfox don't have any permission here on this repo. The best would be: wait for those PRs to be merged, fork `PokeAPI/pokeapi`, run the script, open a PR

Ok @Naramsim, update me when I can go! 
In the meanwhile I'm working on the script, It seems to work like a charm.

![ScriptFixingPokemonSpecies](https://user-images.githubusercontent.com/15571805/212321276-a52e0786-1c8c-40a1-83f0-cec01c431c63.png)

**Comment by tillfox** [comment]
> > If you know the correct ID feel free of submitting a PR fixing the order and the gaps
> 
> Perfect, It will be easy to create a script to fix this, but there is a problem. This change will affect all these relations:
> 
> * encounters (pokemon_id)
> * pokemon (id, species_id)*
> * pokemon_abilities (pokemon_id)
> * pokemon_form_generations (pokemon_form_id)
> * pokemon_form_names (pokemon_form_id)
> * pokemon_forms (id, pokemon_id)*
> * pokemon_species (id, evolves_from_species_id)*
> * pokemon_species_flavor_text (species_id)
> * pokemon_species_names (pokemon_species_id)*
> * pokemon_stats (pokemon_id)
> * pokemon_types (pokemon_id)
> 
> * = Contains Paldea Pokemon data in master
> 
> Just the ones with star could give problems related to concurrency, but if someone else merges changes made using the wrong Ids from another branch, we'll have inconsistent data...
> 
> In addition to that, do I have permissions to directly push a branch on pokeapi, or should I just send you the updated files, so you can commit them? @Naramsim

@Naramsim sorry to bother you again, can you confirm me that these relations that I mentioned before are the only ones that contain ids of pokemons from Paldea? If you confirm this, I know that I have to focus only on these. Thanks in advance for the answer!

**Comment by giginet** [comment]
I read your discussions. 
I think first it’s better to merge current PRs #796 and #805.

After mersing them their IDs are remapped at all.

This process seems to be work well👍

**Comment by tillfox** [comment]
> > @Naramsim sorry to bother you again, can you confirm me that these relations that I mentioned before are the only ones that contain ids of pokemons from Paldea? If you confirm this, I know that I have to focus only on these. Thanks in advance for the answer!
> 
> Can't confirm, an analysis has to be done. And I don't have time 😥

Got it! So, I made the script to fix the ids of Pokemons from Paldea in these relations: 

- encounters (pokemon_id)
- pokemon (id, species_id)*
- pokemon_abilities (pokemon_id)
- pokemon_form_generations (pokemon_form_id)
- pokemon_form_names (pokemon_form_id)
- pokemon_forms (id, pokemon_id)*
- pokemon_species (id, evolves_from_species_id)*
- pokemon_species_flavor_text (species_id)
- pokemon_species_names (pokemon_species_id)*
- pokemon_stats (pokemon_id)
- pokemon_types (pokemon_id)

If someone knows other relations that contains pokemons from Paldea with wrong ids, report them here, so I will extend the script!

Now, while the other pull requests are waiting to be accepted I'll refine and fix my script properly... Please notify me when I can apply the script, as soon as possible, before other data is added to the relations using wrong ids!

**Comment by tillfox** [comment]
@NathanGuidry I spotted an error in the csv; Gholdengo id in pokeapi is 977, but it should be 1000. The line "977,1000" should be added to the file. if you can, please check if there are other things missing, so when I will apply the script there won't be errors left... Thanks in advance!

**Comment by NathanGuidry** [comment]
@tillfox I think some data was lost when i converted it to csv for some reason cause i see quite a few things missing. I will change it when i get the chance this evening

**Comment by NathanGuidry** [comment]
Apologies, I double checked all the data and that was the only error. 
[wrongIDs.csv](https://github.com/PokeAPI/pokeapi/files/10416107/wrongIDs.csv)

**Comment by tillfox** [comment]
> Apologies, I double checked all the data and that was the only error. [wrongIDs.csv](https://github.com/PokeAPI/pokeapi/files/10416107/wrongIDs.csv)

Perfect, thanks!

**Comment by tillfox** [comment]
Script done!

![ScriptDone](https://user-images.githubusercontent.com/15571805/212491565-e1f1ca75-c5d6-44c5-967e-fc8bba76e312.png)

**Comment by Naramsim** [comment]
Hello everyone! @giginet's PRs are merged! 

Can you update your master and re run your tests? 

Many thanks!

**Comment by tillfox** [comment]
> Hello everyone! @giginet's PRs are merged!
> 
> Can you update your master and re run your tests?
> 
> Many thanks!

Done @Naramsim! I don't know if it was needed, but I did a Pull request too... Update me if something is wrong!

**Comment by tillfox** [comment]
@Naramsim so is everything ok with data?

**Comment by Naramsim** [comment]
> @Naramsim so is everything ok with data?

I guess yes! Can you test a bit the API? 

@simonorono you can submit the other sprites i think

**Comment by NathanGuidry** [comment]
the pokeapi/pokemon-species links still return the incorrect pokemon including #980 and #987 in which still dont exist

**Comment by tillfox** [comment]
The species id in the csv is right, so I guess that the problem is with order, which I didn't update.

![Problem](https://user-images.githubusercontent.com/15571805/212850284-b1090913-4891-468d-8d58-e909a0f9f21d.png)

Right now I don't have time to fix it, but it's a very simple problem to fix with the script

**Comment by Naramsim** [comment]
Hi! The API didn't get updated. Can you please try tomorrow? 

It would be nice if you could also update the `order`

**Comment by Naramsim** [comment]
Sorry, GitHub Mobile glitched and i saw 3 comments from @tillfox, all the same. So i delete one. But @tillfox only wrote one so i basically delete his comment.

**Comment by tillfox** [comment]
Questa è censura @Naramsim! Apart from jokes, I'll fix it now I guess...

**Comment by tillfox** [comment]
Ok, sad news, I can't fix this problem by script, because the order is something that has to be updated manually, since the order is not just related to pokemon ids, but to their evos and pre-evos too. So it needs a human intervention, or a more complicate script that I don't have time to write by now... I'll just close the issue and open a new one!
