### ISSUE TITLE
Wrong image data for gmax shiny forms

### ISSUE THREAD

**Issue by FallenDeity** [PokeAPI/pokeapi#814]
Image data discrepancy for eternatus eternamax.
I was working with my pokeapi wrapper https://pypi.org/project/pokelance/ just randomly testing when i noticed the issue
```py
OfficialArtwork(front_default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10190.png', front_shiny='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/10190.png')
```
for front_shiny i was getting pikachu gigantamax image i queried the data manually and checked
```json
{"official-artwork":{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10190.png","front_shiny":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/10190.png"}}
```
In short pikachu gigantamax showing up where eternatus eternamax is expected.

**Comment by FallenDeity** [comment]
Also small note to add it seems this issue is not just with eternatus but almost all gmax data so far what i checked with front_shiny art work is coming of wrong sequence at least those i checked charizard gives eevee cinderace gives toxtricity and so on...

**Comment by FallenDeity** [comment]
What exactly am i supposed to fix and how cause the issue seems to be due to wrong order of images in sprites probably in the shiny folder. A similar effect due to that is here.
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/10196.png
this is the eevee gmax shiny image i found in the sprites with id 10196
https://pokeapi.co/api/v2/pokemon/eevee-gmax
and data shows 10205 so when api tries to query to 10205 endpoint for shiny it raises 404 which cause null in the data similarly most likey due to the mis id'ed images they are reassigned to wrong pokemons.

**Comment by Naramsim** [comment]
Oh, I think the best would be to simply rename the images over at https://github.com/PokeAPI/sprites I hope there won't be too many

If you could help us with that, we would really appreciate it!

**Comment by FallenDeity** [comment]
Ok so back to this issue on the official sprite artwork first of all i checked the images its mostly fine till 10157 by mostly there are still a few missing images and wrong sprites which i have compiled and arranged below
[erros.csv](https://github.com/PokeAPI/pokeapi/files/10471414/erros.csv)
but however from 10158 pandemonium breaks out and till 10271 all images are disordered the shinies from 10158 onwards all show in wrong order instead of renaming all of them it would be better to reupload and overwrite if thats fine by you i can compile a csv for solutions for both above csv issues and the shiny order problem issues

**Comment by FallenDeity** [comment]
also forgot to mention about last 30 or so sprites are missing from repo so mostly 10241 aroundish

**Comment by Naramsim** [comment]
Hi, the best would be of you could open a PR with your fixes. You can decide the method to use, so overwriting files works well

**Comment by FallenDeity** [comment]
@Naramsim i have fixed the above issue and made a pr https://github.com/PokeAPI/sprites/pull/99 please take a look

**Comment by FallenDeity** [comment]
Also any update on pokemon ids disparity in paldea/gen 9 if thats fixed i can try and add gen 9 sprites as well

**Comment by Naramsim** [comment]
@FallenDeity , the `id`s are now fixed and follow the Pokemon standard

**Comment by FallenDeity** [comment]
okie ill start adding the gen9 sprites btw wanted to ask from when the changes will be reflected in the api

**Comment by Naramsim** [comment]
I think gen9 is already in the API and also your changes from the other PR

**Comment by FallenDeity** [comment]
the api show some cached results I think as changes aren't reflected yet as some sprites results are still not shown even when they exist in repo say for example 10208 dosent show front_shiny as for gen 9 data only official artwork front_default exists other ones needs to be added as well

**Comment by Naramsim** [comment]
ahhh, right! I have to rebuild

Well, I just merged a PR, so your data will be live in ~2h

**Comment by FallenDeity** [comment]
@Naramsim made a pr added all shiny sprites for official artwork was currently not able to find source for home and dreamworld sprites any idea about sources for those and gen 5 type sprites under main sprite field.

**Comment by Naramsim** [comment]
I tried searching for dreamworld svg once but didn't find anything. Tried for the pngs but didn't find quality sprites anywhere. I think they weren't produced by the original author. For Home, I don't have any clues.
